<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_email</name>
   <tag></tag>
   <elementGuidId>3d138ac2-362e-4890-a2a5-900f68e580e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/flutter-view[1]/flt-text-editing-host[1]/input[@class=&quot;flt-text-editing transparentTextEditing&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.flt-text-editing.transparentTextEditing</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9c463fb-0f5b-420b-a5bd-163d14c621b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8e7a6036-56c5-4162-9c44-7fbf3b1e55dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e5cc7cac-02a5-46e3-8b8f-7988366173e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4af395f2-3e08-48d4-9e54-5a58527bc671</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flt-text-editing transparentTextEditing</value>
      <webElementGuid>50d5cafa-3baf-44b0-a9ac-abb1a1d440eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/flutter-view[1]/flt-text-editing-host[1]/input[@class=&quot;flt-text-editing transparentTextEditing&quot;]</value>
      <webElementGuid>8fb70bc6-e447-4f19-ac1a-f509ab7af1e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0eff8922-f205-4197-b6b1-33c14b594692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
